// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxyI38mRnQrG_avkNACg0Pms47rt10TKw',
    appId: '1:200942623965:web:41b54b210214a9ecf58f34',
    messagingSenderId: '200942623965',
    projectId: 'chat-app-a1523',
    authDomain: 'chat-app-a1523.firebaseapp.com',
    storageBucket: 'chat-app-a1523.appspot.com',
    measurementId: 'G-D86XHDX4T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJlaUnu8PANmyg4Ky4KFEtWs5LNCwDyhY',
    appId: '1:200942623965:android:1d1251ad855f1429f58f34',
    messagingSenderId: '200942623965',
    projectId: 'chat-app-a1523',
    storageBucket: 'chat-app-a1523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQxKYiVp8vW6VQNR7ADZlS1AXz80hRfc',
    appId: '1:200942623965:ios:6647423e6725af3ff58f34',
    messagingSenderId: '200942623965',
    projectId: 'chat-app-a1523',
    storageBucket: 'chat-app-a1523.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
